import Navbar from '@/components/navbar/navbar';
import '@/styles/globals.css';
import { Syne } from 'next/font/google';

export const metadata = {
  title: 'Me',
  description: 'Generated by create next app',
};

const syne = Syne({
  weight: ['400', '500'],
  subsets: ['latin'],
});

export default function RootLayout({ children }) {
  const currentPage = children.props.childProp.segment;
  return (
    <html lang="en">
      <body
        className={`${syne.className} ${
          currentPage == 'home' ? 'bg-black-70%' : 'bg-white'
        } relative`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
